app/urls.py
from django.urls import path

from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name="index"),
]

bizland/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render


def index(request):
    context = {
        "page_title": "From Index Page",
        "title": "BizLand Theme"
    }
    return render(request, "app/index.html", context)

app/templates/app/about.html
{% load static %}
{% block content %}

    <section id="about" class="section section-about grey lighten-3 center scrollspy">
        <div class="container">
            <h2>About JDEVS</h2>
            <p class="flow-text">
                We're a Mexican software development company with the aim of providing quality tailored products
                for your projects.
            </p>
            <div class="row">
                <div class="col s12 m6">
                    <img src="{% static 'images/renee.png' %}" alt="" class="responsive-img circle">
                </div>
                <div class="col s12 m5 offset-m1">
                    <br>
                    <ul class="collection with-header z-depth-4">
                        <li class="collection-header">
                            <h5>Services</h5>
                        </li>
                        <li class="collection-item">
                            <i class="material-icons left">check</i>
                            Web App Development
                        </li>
                        <li class="collection-item">
                            <i class="material-icons left">check</i>
                            Mobile App Development
                        </li>
                        <li class="collection-item">
                            <i class="material-icons left">check</i>
                            Professional Advise
                        </li>
                        <li class="collection-item">
                            <i class="material-icons left">check</i>
                            Graphic Design
                        </li>
                        <li class="collection-item">
                            <i class="material-icons left">check</i>
                            Spanish-English Translation
                        </li>
                        <li class="collection-item">
                            <i class="material-icons left">check</i>
                            Linux System Hardening
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block css %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
         <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/162ff428c2.js" crossorigin="anonymous"></script>

    <title>{{ title }}</title>
</head>
<body id="home" class="scrollspy">

{% block content %}

{% endblock %}


    {% block javascript  %}
        <script
        src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous">

        </script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <!-- Compiled and minified JavaScript -->
{#  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>#}
        <script src="{% static 'js/materialize.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js"></script>
        <script>
            $(document).ready(function() {
                //Custom JS & JQuery here

                // Init Sidenav
                $('.sidenav').sidenav();

                // Init Scrollspy
                $('.scrollspy').scrollspy();

                // ScrollFire
                const options = [
                    {
                        selector: ".main-text", offset:0, callback: function (el) {
                            Materialize.fadeInImage($(el))
                        }
                    },
                    {
                        selector: ".navbar-fixed", offset: 1500, callback: function () {
                            $('nav').removeClass('transparent')
                            $('nav').addClass('blue-grey darken-3')
                        }
                    },
                ]

                Materialize.scrollFire(options);

                const position = [42.361145, -71.057083]
                const centerPosition = [42.377815, -71.981133]

                function showGoogleMaps() {
                    // Map positions
                    const latLng = new google.maps.LatLng(position[0], position[1])
                    const centerLatLng = new google.maps.LatLng(centerPosition[0], centerPosition[1])
                    // Map options
                    const mapOptions = {
                        zoom: 12,
                        streetViewControl: false,
                        scaleControl: true,
                        mapTypeId: google.maps.mapTypeId.ROADMAP,
                        center: centerLatLng
                    }
                    // Create map
                    map = new google.maps.Map(document.getElementById('googlemap'), mapOptions)

                    // Show Marker
                    marker = new google.maps.Marker({
                        position: latLng,
                        map: map,
                        draggable: false,
                        animation: google.maps.Animation.DROP
                    })
                }

                // Maps event listener
                google.maps.event.addDomListener(window, 'load', showGoogleMaps)

            })
        </script>
    {% endblock %}

</body>
</html>

app/templates/app/boxes.html
{% load static %}

{% block content %}

    <section id="services" class="section-boxes center scrollspy">
        <div class="row">
            <div class="col s12 m6 l3 blue white-text box">
                <i class="material-icons medium">show_chart</i>
                <h4>Grow Your Business</h4>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi esse natus nesciunt numquam qui
                    quia, quos rem repellendus tenetur veritatis.
                </p>
            </div>
            <div class="col s12 m6 l3 purple white-text box">
                <i class="material-icons medium">people</i>
                <h4>Manage Your Processes</h4>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi esse natus nesciunt numquam qui
                    quia, quos rem repellendus tenetur veritatis.
                </p>
            </div>
            <div class="col s12 m6 l3 teal white-text box">
                <i class="material-icons medium">verified_user</i>
                <h4>Tailored Apps to Your Needs</h4>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi esse natus nesciunt numquam qui
                    quia, quos rem repellendus tenetur veritatis.
                </p>
            </div>
            <div class="col s12 m6 l3 amber darken-4 white-text box">
                <i class="material-icons medium">account_balance</i>
                <h4>Need an Advise?</h4>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi esse natus nesciunt numquam qui
                    quia, quos rem repellendus tenetur veritatis.
                </p>
            </div>
        </div>
    </section>

{% endblock %}

app/templates/app/contact.html
{% load static %}
{% block content %}

    <section id="contact" class="section section-contact center scrollspy">
    <div id="googlemap"></div>
    <div class="container">
        <div class="row">
        <div class="col s12 m6 offset-m6">
            <div class="card-panel z-depth-5">
                <h4>Contact Us</h4>
                <form action="">
                    <div class="input-field">
                        <input type="text" id="name" placeholder="Name">
                        <label for="name">Name</label>
                    </div>
                    <div class="input-field">
                        <input type="email" id="email" class="validate" placeholder="Email">
                        <label for="email">Email</label>
                    </div>
                    <div class="input-field">
                        <input type="text" id="phone" placeholder="Phone Number">
                        <label for="phone">Phone</label>
                    </div>
                    <div class="input-field">
                        <textarea id="message" class="materialize-textarea"></textarea>
                        <label for="message">Message</label>
                    </div>
                    <input type="submit" value="Submit" class="btn blue-grey">
                </form>

            </div>
        </div>

        </div>
    </div>
    </section>

{% endblock %}

app/templates/app/footer.html
{% load static %}
{% block content %}

    <footer class="page-footer blue-grey darken-1">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5>Location</h5>
                <p>JDEVS.MX</p>
                <p>Pantaleon Leal 194, Tepatitlán, Jalisco, MX</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Site Map</h5>
                  <ul>
                      <li><a class="white-text" href="#home">Home</a></li>
                      <li><a class="white-text" href="#about">About Us</a></li>
                      <li><a class="white-text" href="#services">Services</a></li>
                      <li><a class="white-text" href="#testimonials">Testimonials</a></li>
                      <li><a class="white-text" href="#contact">Contact</a></li>
                  </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright blue-grey darken-4">
            <div class="container">
            JDEVS © 2020
            <a class="grey-text text-lighten-4 right" href="#home">
                <i class="material-icons left">keyboard_arrow_up</i>
                Back To Top
            </a>
            </div>
          </div>
        </footer>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
    {% include 'app/navbar.html' %}
    {% include 'app/boxes.html' %}
    {% include 'app/about.html' %}
    {% include 'app/testimonials.html' %}
    {% include 'app/contact.html' %}
    {% include 'app/footer.html' %}

{% endblock %}

app/templates/app/navbar.html
{% load static %}

{% block content %}

    <header class="main-header">
    <div class="primary-overlay">
        <div class="navbar-fixed">
            <nav class="transparent">
                <div class="container">
                    <div class="nav-wrapper">
                        <a href="{% url 'app:index' %}" class="brand-logo">JDEVS</a>
                        <a href="#" data-target="slide-out" data-activates="mobile-demo" class="button-collapse sidenav-trigger">
                            <i class="material-icons">menu</i>
                        </a>
                        <ul class="right hide-on-med-and-down">
                            <li><a href="#home">Home</a></li>
                            <li><a href="#about">About Us</a></li>
                            <li><a href="#services">Services</a></li>
                            <li><a href="#testimonials">Our Moto</a></li>
                            <li><a href="#contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>

        <!-- Sidenav -->
        <ul id="slide-out" class="sidenav">
            <h4 class="blue-grey darken-3 center">BizLand</h4>
            <li><a href="#home">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#services">Services</a></li>
            <li><a href="#testimonials">Our Moto</a></li>
            <li><a href="#contact">Contact</a></li>
            <li>
                <div class="divider"></div>
            </li>
            <li><a class="waves-effect" href="#">Login</a></li>
        </ul>

        <!-- Section: Showcase -->
        <div class="showcase container">
            <div class="row">
                <div class="col s12 main-text">
                    <h5>Need a Web or Mobile App?</h5>
                    <h1>Right Place To Start</h1>
                    <p class="flow-text">
                        To take your business to the next level with our services that will improve
                        your overall business.
                        <br><br>
                        <a href="#about" class="btn btn-large waves-effect white black-text">
                            Learn More
                        </a>
                        <a href="#contact" class="white-text">
                            <i class="material-icons medium scroll-icon">arrow_drop_down_circle</i>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    </header>

{% endblock %}

app/templates/app/testimonials.html
{% load static %}
{% block content %}

    <section id="testimonials" class="section section-testimonials blue white-text center scrollspy">
    <div class="container">
        <h2>Our Moto</h2>
        <div class="row">
            <div class="col s12 m4">
                <div class="card grey lighten-3 black-text z-depth-4">
                    <div class="card-content">
                        <p><em>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam architecto aspernatur at
                            ea earum et, maiores quae quod tempore ullam!
                        </em></p>
                    </div>
                    <div class="card-action">
                        <p>Nikola Tesla from Tesla Inventions</p>
                    </div>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="card grey lighten-3 black-text z-depth-4">
                    <div class="card-content">
                        <p><em>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam architecto aspernatur at
                            ea earum et, maiores quae quod tempore ullam!
                        </em></p>
                    </div>
                    <div class="card-action">
                        <p>Jane Doe from Linux.org</p>
                    </div>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="card grey lighten-3 black-text z-depth-4">
                    <div class="card-content">
                        <p><em>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam architecto aspernatur at
                            ea earum et, maiores quae quod tempore ullam!
                        </em></p>
                    </div>
                    <div class="card-action">
                        <p>Tony Stark from Marvel</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>

{% endblock %}